### ISSUE TITLE
Getting you Django project running: Post virutal machine setup instructions

### ISSUE THREAD

**Issue by samdasoxide** [rocketpod/django-starter#1]
Before running the development server, there are some few steps are needed for to get your first Django project running. 

-  Update the packages `sudo apt-get update`
-  Install `python-pip` `python-dev` `build-essenstial`
-  Install `virtualenv` and `virtualenvwrapper` 
-  Add `workon` command for activating the environment to `.bashrc` by adding the following lines
     ```bash

     export WORKON_HOME=~/Envs
     source /usr/local/bin/virtualenvwrapper.sh
     ```
-  Create a virtual environment for project
    ```bash

       $ mkvirtualenv projectname
    ```
-  Activate virtual environment 
    ```bash

        $ workon projectname
     ```
- `sudo pip install django wagtail opbeat django-extentions django-debug-toolbar`
- Setup and configure database. Found this [great guide](https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04).
- Run migrations `python manage.py migrate`
- Create super user `python manage.py createsuperuser`
- Run development server

**Comment by prydie** [comment]
The provisioner should do all of that when you first do `vagrant up development`. Please run `vagrant provision development` and let me know what the output is.

**Comment by prydie** [comment]
Closing as invalid due to confirmation that the Vagrant box wasn't provisioned.
